openapi: 3.0.0
info:
  version: 1.0.0
  title: realmeet
servers:
  - url: 'http://localhost:8080'
paths:
  /rooms/{id}:
    get:
      summary: 'Return a room by ID'
      operationId: find
      tags:
        - room
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the room
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RoomDTO'
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
  /rooms:
    post:
      summary: 'Create a room'
      operationId: create
      tags:
        - room
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateRoomDTO'
        required: true
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RoomDTO'
        422:
          description: Created
          $ref: '#/components/responses/UnprocessableEntity'
components:
  schemas:
    RoomDTO:
      type: object
      allOf:
        - $ref: '#/components/schemas/CreateRoomDTO'
        - type: object
          properties:
            id:
              type: integer
              format: int64

    CreateRoomDTO:
      type: object
      properties:
        name:
          type: string
        seats:
          type: integer

    ResponseError:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        status:
          type: string

  responses:
    UnprocessableEntity:
      description: The server understands the content type of the request entity but was unable to process the contained instructions.